name: Base workflow
on:
  push:
    branches:
      - master

jobs:
  foo:
    name: Foo Job!
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1

      - name: Greetings
        run: |
          echo "hello world"
