name: ECS Deploy
on:
  push:
    branches:
      - step-ecs-deploy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEPLOY_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.DEPLOY_SECRET_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker Image
        run: |
          echo "Building Docker image"
          docker build -t 082982103746.dkr.ecr.us-west-2.amazonaws.com/ghactions-demo:dev .

      - name: Publish Docker Image
        id: push-image
        run: |
          docker push 082982103746.dkr.ecr.us-west-2.amazonaws.com/ghactions-demo:dev
          echo "::set-output name=docker_image::082982103746.dkr.ecr.us-west-2.amazonaws.com/ghactions-demo:dev"
