name: Sequential jobs example
on:
  push:
    branches:
      - multiple-workflows

jobs:
  job-1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Step 1.1
        run: |
          echo "Job 1 my beloved hobbits"
          sleep 10
          echo "End of Job 1"

  job-2:
    name: Job 2
    runs-on: ubuntu-latest
    steps:
      - name: Step 2.1
        run: |
          echo "Job 2 my immortal elves"
          sleep 9
          echo "End of Job 2"

  job-3:
    name: Job 3
    runs-on: ubuntu-latest
    needs: [job-1, job-2]
    steps:
      - name: Step 3.1
        run: |
          echo "Job 3 my strong dwarves"
          sleep 5
          echo "End of Job 3"

  job-4:
    name: Job 4
    runs-on: ubuntu-latest
    needs: [job-3]
    steps:
      - name: Step 4.1
        run: |
          echo "Job 4 my loyal men"
          sleep 2
          echo "End of Job 4"
